
package MathResearch2019.Tests;

import static org.junit.Assert.assertTrue;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;

import MathResearch2019.Errors.InvalidBoardString;
import MathResearch2019.Games.TicTacToeNxN;
import MathResearch2019.Main.ReconfigurationGraph;

public class ReconfigurationGraphTest {
  public ReconfigurationGraph r3x3 = new ReconfigurationGraph((new TicTacToeNxN()));

  @Test
  public void testSize() {
    assertTrue(r3x3.getTotalBoards() + "", r3x3.getTotalBoards() == 5478);
  }

  @ParameterizedTest
  @CsvSource({ "OXXXeeOOe", "OOXeOXOXe", "OeeXOOeXX", "eeOOXeOeX", "eeeXOXeeO", "XOXOeeOOX", "XOOXOXeeO", "eeOeXXOOe",
      "OOXeXeeeO", "eOXOXeeOe", "XOOeXeOee", "XXOOeeOXe", "XOeOXOXeO", "XeeeOXOOe", "eOeOOXeXe", "XeXOXOOOe",
      "eOXXeeOXO", "XOOXXeOee", "eXOOOXeOX", "eOXOeOXOX", "OeeeOeXOX", "OXXXOXOOe", "OOXXXOOXO", "XOeXOXOeO",
      "Oeeeeeeee", "eXeOOeXeO", "XeeOeOeeX", "XOOeOeeXe", "XeOOOXXeO", "eeXeOeXOe", "eeOXOOeXX", "eeOXXeOee",
      "XOXXOeOXO", "eeeeXOXOO", "OeXeXOeeO", "OeeXXOeOX", "eOeeXeOeX", "eOOeOXeXe", "XeXeeOOOe", "eeOOeeOXX",
      "eXeeOeeee", "OeOXOOeXX", "eOXOeOXXe", "OeXeOeeXe", "OeXeeOeeX", "XXOOeeOee", "OOeeXeXee", "eXeOeOeeX",
      "OeeOeeeXe", "XeeOeOOXe", "eOeeOXXeO", "XOOeeeXXO", "eXOOOXeOX", "XOOOeXeee", "OeXXOeeee", "OOeXXeXeO",
      "XeeeOXeOO", "OOeOeXeeX", "XOOOeeeeX", "eXOeeeOXe", "OXeOeXXOe", "OeeOeOeXX", "eOXeeeeXO", "OeeeXOXXO",
      "eeOeeXeXO", "OXOOXXeee", "XeeeeOOeX", "XOXeXOOXO", "eeeeOOOXX", "XXeeeeOOe", "eXeeXOOee", "XOOOeXeee",
      "eeOXOXeee", "XeXOOXXOO", "OOXeOXeXe", "OeeXOOXXe", "eXXOOeeOX", "OXeeOeXOX", "XXOeeXeOO", "OeOOeXeeX",
      "OeOOXeeXX", "eXXeOeOOe", "XOeXXOeOe", "eeeeOeXOX", "XOOOXXeOe", "XOXXeeeOO", "eXeeeeeOO", "XOXOeOXeO",
      "XeXOeOeOX", "XOOOeXeeX", "XeOOXeOXe", "XOeOeOeXe", "XeOOeeeeX", "OeOXXOeeX", "OXeeeOXOX", "XeeeXeeOO",
      "XXeOOeOXe", "eeOXeXOXO", "OXeeOeXee", "eeeOeOOXX", "OeeeeOeXe", "eXXeeOXOO", "OeOXXeOeX", "eXeOeXOOe",
      "OeXXeOeeO", "XOOeeXOOX", "OeOXXOXee", "OeOOeeXXe", "XOOeeOeXe", "XOXXOOOee", "eOXOXeOOX", "XeXeOOXOe",
      "OOeOeXXee", "eOeOeXeOX", "eeeeOeeOX", "XXeXeOeOO", "eXeOeOeOX", "OeXOeOXeX", "eXOeXOeOX", "eXeOXXOOe",
      "eXeOXOeee", "eXOeeOXOX", "OOXXXeOOe", "eeOXOOXee", "eOXOOeOXX", "OXeeeOOXe", "OXXeeOeXO", "OXXOOeXOX",
      "OOXOXXeOe", "eeOOXeXOe", "OXOXOOXee", "XOOOeXeee", "eeOeXeXOe", "OXeXeOXOe", "eeOXeOOXX", "eOOOXXOXe",
      "eXOXeOeOX", "eOeOeeeXe", "XOOXeOOeX", "XeOeOeeeX", "eOeXeeeXO", "XOeeOeOXe", "XOeOeeXee", "OOeXXeeeO",
      "eXOOOXXeO", "XOXOeeeOe", "eeOOeeXeX", "OXXXOXOOe", "OeOeeXOXe", "OOeOeXXXO", "OXeXXOOeO", "OeeOeXeXe",
      "OXOOOXXXe", "eXeOXeOee", "OeeeeeeeX", "eeeXOXXOO", "eXOXeXeOO", "OXXXOeOOX", "OOeeXeXXO", "eeOeXeOee",
      "XXeOeeOXO", "eXeOeOeXe", "XeeeeOOeX", "OeOeXOeXX", "OeOeXOXXe", "XXOOOXeee", "eXOXeOXOe", "eeeeeOeee",
      "OeeXXeOOe", "XXeOeeOee", "OXOeOXeee", "eeXOeeeeO", "XeOeOOXXe", "OXeOXXeeO", "OeXOeeXOX", "XeOeOeXXO",
      "OOeeXXOXe", "XeeOXOOee", "eXXeOeOXO", "eOeeXeXOO", "OOXeeOeXe", "eXXOeOOXO", "OeeXOXOOX", "eeeeXeOXO",
      "XOXOXeOee", "OXOXOOeXe", "XeeOXeOee", "eXOeOXeeO", "OXXXOOOeX", "XOeeXOOXe", "eXeOOXOOX", "XOXOXOOee",
      "eeOeXXOXO", "eeeOXOXOX", "eOXOOeOXX", "OeeXOOXee", "XeXeeOOee", "OOeXeOXXO", "eOXOXXeOe", "XXOeOXeOO",
      "OXOOXXeOe", "eOOeXOXXe", "eeXXeOeeO", "OeXeeXOeO", "eeOeOXeOX", "OXeXOOXee", "XeOOOXeXO", "XOeOeeeXO",
      "OXeXXeOeO", "OeOXXeeOX", "XOeOXXOeO", "eOOXOXeeX", "OeeeeXOOX", "eXeeOOeeX", "OXOXXeOeO", "XXeOOXOXO",
      "XeXOXOOXO", "eOXXeeOOe", "XeeOOeXeO", "eXOeeeOXO", "OOXOeOeXX", "OeeeOeXOX", "eeOOeXXeO", "OeXXXOOOX",
      "eXOOXOeOX", "OOeXeeXee", "OeOXOeeXX", "XOeOeeXOe", "XOeOXOeXe", "eOeXOOeeX", "XOeeXeOXO", "OeOOXOXeX",
      "OeOXeeXee", "OXOXOeeee", "eeOXXOOXe", "eXXeeeeOO", "eXOXeOXOe", "XOOXeOeOX", "XOeOeeeXe", "OeOeeXXeO",
      "eeeOOXeeX", "eeOOeeeXX", "XeeOOXXOO", "OXXeOeXOe", "OeOXOXeXe", "OXeOXeeOe", "OeXeXeOOe", "eXeOXOOOX",
      "OOXeeXeee", "eeXeXOOOe", "OeOeXXeee", "XeXOOXOXO", "OeeeeOXeX", "XOOOXXOXe", "eXeOeXeOO", "XeeOOeeee",
      "eeOeOXXXO", "eOXXOeOee", "OXeeXeOeO", "OXeXOOeeX", "eOeeeXOee", "eXOXXOOOe", "XOeeXOXOO", "XOeeOOeXe",
      "OeeXXOXeO", "eXXeeOeOO", "OOeXXeOXO", "eeOeeXeOe", "OeeeOXeee", "eXOOeXOee", "XeXOeeOee", "OeXeOOeeX",
      "XeOXeXOOe", "eOXeeeXeO", "eeXeOOXOe", "eeXOOeXXO", "OeeOOXXee", "XOeeXeOeO", "eXeOOeeXe", "eOXXeOeee",
      "XOXeOOeee", "XeeeOOOeX", "OOXOeeeeX", "eeeeOeeXO", "eOeXeOXOX", "XOeXOOeeX", "OXeOeXXeO", "eOXeXOeeO",
      "XeeeOeOeX", "OXeeeeXeO", "XOOXXeeOO", "eOeOXOXOX", "OXOOXeXee", "eeeeeeeeO", "OXOOOeXXe", "OXeeXOeeO",
      "OeXOXOeeX", "eeeXOeXOO", "OeXOXXeOO", "OeOeeeOXX", "eeeXXeOOe", "XXeeOeOOX", "OeXeeeOXe", "eXOOOXeOX",
      "OeeXeeXOO", "XOeeXOeXO", "XOOXeeOeX", "eXeXOeOee", "OeeOXeeXe", "eXeOXeOOe", "eOXOXXeOe", "XeeOOeeXe",
      "eOeXXeOOe", "OXXeXOOOX", "eXXeOeeOO", "eeOeOXeXe", "OOeOeXXee", "eeeOXXOee", "OOeeXXOXe", "XeeOOeeOX",
      "XOOOXOeXe", "OOeeeXeee", "XOXeXOeOO", "OeOeeeeeX", "eXOeXOXOe", "OXOeeXOee", "OXXOeeXOO", "eXeOOeeeX",
      "XOOXXeOee", "XOeOOXOXX", "XOOeXXeOO", "XXeXOOOOe", "eeXOeOOXX", "OOXXeeOXO", "eeeXOOOeX", "OXeXOOXOe",
      "XeOeeeOee", "XeOeeOXOX", "XOXeeOeeO", "eXOXOeeee", "XOeOOXXee", "OOeeeOeXX", "eXXOeXeOO", "eXeeOXOee",
      "XXOOeOXOe", "eXOOeXXeO", "OXOOOXXXe", "eOeOXeOeX", "XeXOeeOOe", "OXeXeOOeX", "eeOXOXXeO", "eOeXeeOOX",
      "eXeeOeXOe", "XeeOOXOXO", "OeeXOXOee", "eXeOeXOeO", "eOeeOeXee", "eeXeeeeeO", "OXXeOOXee", "XXeOXeeOO",
      "OeOXeXOXe", "eOXeXXOOe", "XXOeOOXOe", "eOXXXOOee", "eeXeOXOOe", "XeXeOOXOO", "OeOeOXeeX", "eOXXeeOOe",
      "eeeOeXeOX", "OOXeOeOXX", "XXeOOeOeX", "OOXOXeeXO", "eeeeeeOeX", "XOOeeXOXO", "XeOXeOOOX", "eeOXeeOXO",
      "XeOOXeOXO", "eeOOeXOXe", "eeeeOOOXX", "XOeeeXOee", "OeXOeeeeX", "eeOOeeXXO", "eXOXOOeXe", "eXeXOOOeX",
      "XOXeOOeXO", "eeOOXXOXe", "OOXXXeOee", "OOeXOXOeX", "XeOeOOXOX", "eXOeeeOXe", "XXeOeXOeO", "OeeXeOOXX",
      "eeXXeOOOe", "eOeOXeOXX", "eOOeXOXXe", "XOXeXOOOe", "eeOeeXOOX", "eeXXOeeOe", "eOeOeXXXO", "OXXOeOXXO",
      "eeeXOXeeO", "XOOXeOOXX", "eOeOXeeOX", "OeOXeOeeX", "OeOXXeOXO", "XOXOOeXeO", "XOeOXeOee", "eOeXeeXeO",
      "eXeOOXeee", "OeXXeOeee", "OOXOXOeXX", "eOeeXOeee", "OeOeXeeXe", "Oeeeeeeee", "OXeXOeeee", "eOeXOOXee",
      "OeeOXXXOO", "OeeOeXXeO", "eOeeOeOXX", "eeOXOOXOX", "OOeeXOeXe", "XXOeXeOeO", "XOXXXOOOe", "XeeeeXeOO",
      "eeeeOeXXO", "eOeOeXeOX", "OXeXOXOOX", "XeXeOOOXO", "eeeeeeOee", "XeeeeeeOO", "XXOeeOXOe", "eOXXXOOeO",
      "XeeOXOeOe", "eXOOOeXOX", "eeXXOOeXO", "OeOeXeXee", "eeOeeXeee", "eeeeeOeOX", "OXeXeOOXO", "OXXeOXeOe",
      "eeXeeeOee", "eXXOeeOeO", "OeOXXeeOX", "eeXeeOeeO", "eXeOOXeOX", "XeXXOOOXO", "OXeOXeeOX", "eOXXeOOXO",
      "XOOeeXXeO", "OXeeXeXOO", "eOXeeXOeO", "eXOeXeOOX", "OXXXeOOOe", "eXOXeeXOO", "XXOOeOOXX", "eOeeeOXeX",
      "XeOeeXeOO", "eeXeeOOee", "XeOeOOXeX", "eOXeeXOee", "eeXOXOeeO", "eOeeXeXOe", "eeOOXeXee", "XeOeOXeOe",
      "eXeXOOOXe", "OeXXeOOXe", "XeXOeOXOe", "eeeXXOOXO", "eOXXOXOeO", "OeOXXeXeO", "XOXeeeOeO", "OXXXOeOee",
      "eeeXOeOee", "eeXeeeeeO", "eOOXOOXXe", "OXOXXeXOO", "XOOOXOeXe", "XXeeeOOeO", "XeeOXeOXO", "eeXOOXOee",
      "OeXOXeeee", "eOXeOXOXO", "OeXeOeeeX", "eXOOXXeOO", "OeeeXXOOe", "XOeXeeOeO", "eeOOXXOXe", "XOOXeXOXO",
      "eOeOOXXeX", "XeXOOXeOO", "eOXOXXeOO", "OXeXXOeeO", "OeXeOOXXe", "eeeOXOOeeeXXOOXe", "eOOXOeeOXXeOeeeX",
      "eOXOOeOOOXeXXeeX", "OeXXeOXOOOOeeXXX", "XeOeOXXOeOeXOOXe", "XOOXOOeeXOXeeXXO", "OOXeXeeOXOXOXeXO",
      "eOeeXOXeOeXXXOOe", "XeOOOeeXOeXOXeXO", "OeeXeOXOXeXOeeOX", "XOOXOeOeeXXOOXee", "OeeXOeOeOXeXXeee",
      "OXeXeXOOOeeeXeXO", "XeXeeOXOXeeXOOeO", "eeXXOeeOXXeOeOeO", "eeXXOXOOXOOXOXXO", "eXeXXXOOeeXOOOOX",
      "XOeXOOeeeOOXeXee", "OXXeeeXOOOOeXeee", "XeOXOXOXOeXeOXOe", "XOeeXOeOOeeeOXXe", "eeOeeXOXOXeeOOeX",
      "eOOXXeeeXeOeeXOe", "OXeXOXeeOeXOXeeO", "OXeOOXXeOeXeXOXO", "eOXeXXOXOOXeXOeO", "eOeXXXXOeeOOeeOX",
      "eeXXOOXOeXXOeOOX", "XOeeXOXOOXOXeOee", "eXOOOXeXXOOOXXeO", "OeXOOeeXOeeOXXXO", "OeeXeeXeeeOXOeOe",
      "eOeeOXXOOeXeOeXe", "eOeXeOeeXeXOeOOX", "XXeXeeXOXOeOeOOe", "eeeXeeeOeOOeeXXO", "XOeOeeeOXXXOeeOX",
      "eXeOeXeeOXOeeeee", "XOXOOeeOeXXXXOeO", "eeOXeeXOXOXeeOeO", "XOOXOXeOOeXXXXOO", "OXOeeXeOOeeeeXXO",
      "XeOeXXXOeeOXOOXO", "XeeeeeOOOOeXeOXX", "OXeeOXeOeXXXOeOe", "eOeeeXeXeXXeeOOO", "XeOOXOOXOeXeXeee",
      "OeOeeeXOOOXeeXXX", "eXeXXeOeOeOXOOXe", "eOeOeXOXeOXeXeeO", "OXXeOeOXeOeeeeee", "eeeXXOOeXXXeeOOO",
      "OOXOXXOXOOXXeeee", "XOeeeOXOeeOXXeeO", "OXOeeXeeOOXeXXeO", "OeXOOXeXXOXOeeee", "XOeOXXeeOeOOeeXe",
      "OOeeXOeeOOeXXXee", "eeOeOXXXOOXOeXOX", "XXeOeOOXeeXXOeOO", "eXXOeOOeXeeOXeeO", "eeOeeOOXeOeOeXXX",
      "eOXeXOeeOeeeeeeX", "eOeXXXeeeOOeOeXO", "XXXeeOeeOOXeOXeO", "eOeOeeeOeXXXOeee", "OOeXOXXeOOXOeeeX",
      "OOeOXOXXOXOeOeXX", "OeOXeXOOXXOeeXeO", "eXXOeeOXeeOeOOXX", "eOOOXXOXeXOXeeee", "OXeOeOXOOeXeeeXe",
      "eeOOeXeOeXOOXeXe", "eXeeOXOXOeeXOXOO", "XeXXXOOOOOeeeOeX", "XOeXOXeOOeeeeeXO", "OeeOXeXOOOXeOeXX",
      "eXXXeeOeOeOeeeeO", "OeXeOXXeeeeOOeee", "XXeOOXOeeXXeeOeO", "OXXXOeOeOOXOXeXe", "XOeeOOXOXXXOeOee",
      "eOeXOXXOXeOeOOXe", "OOeeeeeeeeeXXeeO", "eOeeXXOXOOeOXXOX", "eXeOOXXXeeOXOeOe", "eXXOXOXXeOOOOXOX",
      "eeXeOeeOeeeOOXeX", "OOXeeeeOXeOeOXXX", "OeeeeOOXOXOXXOeX", "eeOeXeeeeOOXeOXe", "eeXOeOXeOeXXeOeO",
      "eXOeeeeeeXeOeeee", "eXXeOeOeOOXXXOeO", "eeeXeOOOXOXXeXeO", "eOXOOXOXeXXeOOeX", "eOXOeXOXOeXeOXOe",
      "eXOXOXXOOeXXOOXO", "eOXXOeeXeXOeXOOO", "OeeXeXXOXeeOeXOO", "OeOeOeXOXXXOXOee", "eeOeXOXeXOXeeOee",
      "eOXeXOOXXXOOXeOe", "eXOXOXOeOOOXeXeX", "OXeXXOeOeXXXOOOe", "eeXOXeOXOeeOeOXX", "OeXOOXOeeeeeeXXe",
      "XOXXeOOeeeXeOXOO", "XOeeeeeOeOXXOOXe", "OXOXXXOOeeeeOXOX", "XeOeXXOeeeXeOeOO", "eXOXeXeeOXeOXOOe",
      "XXOeXeOeeeXOXOOO", "OeeXeOXeeOeOXeOX", "XOXOXeOeXeXeOeOe", "eOeXeXOeXOeOeXeO", "OeXXeOOOeXeeOXXe",
      "XXXeeOXOeXeeOeOO", "eOOeXXOXeXeOeXOe", "eeOXeeeeOeOXeXeO", "XOXXeOeOeXOXXOOO", "XeXOXeeXOeeeOOXO",
      "OeXeOeXOeXXeOOOX", "OeXOOXOXeXXeXOOe", "eOXeeOeOeeeOeXeX", "eOXXXeXeXXOOOOeO", "eeXeXeeOXeeXOOOe",
      "XOOXOXOXeXOOXeeO", "XOeOeOOeXXOXeOeX", "eOXXeOeeOOeOXeXe", "OXXeOeeeeOXXOOXe", "XOOXeOeeXeXXeOOe",
      "OOeeXeOeXOXXeeeO", "OeeXeOOXOeXeeXOX", "OeeOXeXXOOOXXOeX", "OeeOXOeOXOeXXeOX", "XOOXOOXOXXXOOeee",
      "eOeXOOeXeXeXOXeO", "OXOeeeeXXOeXXOOe", "OeeXeeeeOXXOXXOO", "OeOeXXXOXOeOOXee", "XXeOeOeeXOeOeOeX",
      "XOeXeeeXOeOeeOXO", "XOOeOXXOXOeeXOXO", "XXOOOOXeOXXXeeOe", "eXeOOXOOXeeeeXXO", "OeOeOXeeXOeXeXOe",
      "XeeXXeeOOOOeXOXe", "XXXeeOOeOXOXXOOO", "XOOeeeXOOXOeeXXO", "OXXeeOeOeOeeOXXe", "OeeOeOOOXXXeXeXO",
      "XOXXOXOeeOeOXOXO", "eeOOeOXXeeeeeOeX", "eXOeeOOeXeXXeeOe", "XOOeeeXeOeOXeXOe", "eOXXOOeeXeXOeXeO",
      "OOeXXOXOeOOXeeXe", "OeeOOeXeXeXeOeeX", "eeeOOeXXXOeXXOOe", "OeeXOOeeXXeOeXXO", "XeOeeeXXOOOXeOXO",
      "XeeOXeXeOeeOeeeO", "eOeOeeOeXOXOeXeX", "XOeOeOXOXXXOeeee", "XeOXOeOXeXeOeOeX", "XeXeOeOXeOOeXeOX",
      "OXOXXeOXXOXOXOOe", "XeeOeOXXOeXeOOeX", "eeOOXeXOXOXeeOeX", "OeeOeXOeXOeeeXee", "eXeeOOeXeOXOXOeX",
      "eXeOOXOXOeeXOeeX", "XXOXOeXOeOeOeXXO", "XeeeeOeOXeeOeeXe", "eeeOXeOXXXOeOeOe", "OXeOOeOeeXXXXeOe",
      "XXXOOXOeOeeeeeXO", "XeOeeeeXXOXeOeeO", "OXOXOXeOeXeeOeeX", "eXOOOOeOXeeeeXeX", "eXOXXeeOXXeOXOOO",
      "XeXOXeXeOOeOXOOe", "OeOOXeXeXOOeOXeX", "OOXeXeeOeXOOeXXO", "XeOOeOeXeeOOXXeX", "eeOOOeeXeXOXXXeO",
      "eOXOOeXOOXXXeeeO", "eeXOeXXeeXOeOOOe", "eOeOeOXOOeXOXeXX", "eOXOeXeOXXOeOOXe", "OXeOXXOeXeOeeXOe",
      "OeOOeOeeXXeXeXXO", "XOXeOXXOOeeeeOXO", "eOXOeeOXXOXXeOOe", "XOXOXXOXOeeeOeee", "OOXeeXeOOeeXeeee",
      "eXXeeOeeOeOeXOee", "eOOeXXeOeXOXOXeO", "eeeeOOOXeeXeOXXO", "OeeeXeOXXeOXOXeO", "OXeOeXXXOOXOXOee",
      "XXOeOeeXOeXXOeOe", "OeOeXXXOXeOOXOee", "OXeOXeeOOXXeOeee", "OOOeXXeXeXeeeXOO", "OOXeXeeeXOXOeOeX",
      "OXOXOXXXOeOOXOeX", "eOOXeXeeeeOeOeXe", "OeXeXeeeOOXeXXOO", "OXXOOOXOeXOeXOXe", "XOeOeXeOeOOOXXeX",
      "OXeXXOeeOeXXOXOO", "eeeXOOeOeOXXeXXO", "eXXOXeXXeXOOOOeO", "OXXeOOeOOeXXXOeX", "XOOeeXOeXOeeeXee",
      "XXeeOeOXOeeXeeeO", "XeOXXeOXOXOOeOXO", "eXOeXOOXOXOeXXeO", "OeXeeeeXOeXOeXOO", "XOOXXeeOXeeOeOeX",
      "eeeOXOXOOeXeXeXO", "eeXeeOXOOXeeXeeO", "XXOeOOOXOXeeOOXX", "OXXeeOOeOeeOOXXX", "OOeXOXXOeeOXeeXe",
      "OXeeeOeXeXOeOOXe", "XOeOOXXeOeOeXOeX", "OXeOOXOXXXeeeOOe", "eeOXeOXeXOOeOXee", "eOXXeXOOeeeeOXeO",
      "eeeeeeXOOeOeXeee", "OOOeOXXeXeeeeXeO", "XeeXeOXOeOeeXeeO", "XeOeOXXOeOOXXOee", "eXeOOeeOOXeeOXXX",
      "eeeXeOXOXeeXOOee", "eeXOeeeeOOXeXeXO", "OOXXeXXOOeeXOXOe", "XeeOeeXOOeXOOXeX", "XOXOeeeOXXeeOOee",
      "OOeXeXXOXXOeeeOe", "XOOeXOXOeOeOeXeX", "XOOOOXeXOXeeXeeO", "OeXOXXeeeOXOeeee", "XeXOeeOeOXeOXeOX",
      "XOXXXOOeeXXOOeOe", "XOeeeeXXOeOOeOXX", "XOXeeeOOOXOXeXXO", "XOXeXOXXeOeOOeOX", "eOeeeXXeeXeOOOXe",
      "XXXOOOOeeXOOOXeX", "eXOXeeXXOOeOOXXO", "eeeeeXeeXeeeOOeO", "eXOOeOXeOOeeXeXe", "XXOOOXXXeOOeXeOe",
      "OOeeeeeeOXXXeOee", "eOXXeeXeXOOOXOeO", "OOXeeeOXXOeeeXOe", "OXeOOXOeeeeXeXOe", "eeXXOXeeOeeXeOOO",
      "OXOeOXXeeOOXXOXe", "XOOeeXXOeOeeXeeO", "XXeOOeXeOOOXOXeX", "eeeeXOeOeeXeOXOe", "eOeeOOXOXXeeeXeO",
      "eOOeXOXOeXOOeXXX", "eOOeOXXeeXOeXOOX", "XXOOXeeOeOOOXXee", "XeXXOeOOeeXOXOee", "eeOOXOeXOXeXOOXe",
      "OOeeXeeXOeXXeOeO", "eeeeeOeXeOXOXXOe", "XeeeOOXeeXXOOOOX", "OeOeXOXeeXXXXOOO", "XOeXXOOeeXOeXOOe",
      "eeeXeXXeOOeeeeeO", "eXOOXOXeXeOeeeee", "OXOeOOXeOXeeeOXX", "XOXeOOeOeXXXOeXO", "XeXXOeOeXXOeeOOO",
      "XOOeeeXOXOOOeXXX", "XOXOeeXOXXeeOOee", "XeXXOXOXOOeXXOOO", "eOeOXXOOeeXXeOOX", "eOXOOXXOOeeeXXeO",
      "eXOOXeOXOOXOeeXX", "OeOeeOeeeXXXXOOe", "eeOOeOeeeeXXXOeX", "eOOXeXeXOeeeeXeO", "XXXeeOOOXeOeOOXX",
      "XeXeXXeOOeOOOXee", "eXOXXOeOOOeXeXXO", "eOeeeOOOeXXXXXOe", "OeXOOXeeXXOeXOOe", "eXXXXOOOXOeXOOeO",
      "XOXOOOeOXXeXXOee", "eXOOOXXXOXOOXeXO", "OeXeXeeOeXeeOeXO", "XOeeXXOXOXeOeOee", "XeXeOeXeeXOeOOeO",
      "eOeXeOXOXeOOeOXX", "XeOeOXXOeeOeOeXe", "OOeXXeOXOeXXOeee", "XeXOeOeeeXXOeOeO", "XOeOOXOXeeOeeXOX",
      "XeOXeXOXOXOOeOXO", "eXOXOOOeeeXeXOOX", "eeeOeeeXeXXOOeeO", "eeeeeXOeXeOOXOeX", "eeXOXeeeXeOeeeOe",
      "OeeXOOeOeeXXXOOX", "eeeXeXXXXOeOOeOO", "XOOXeXeOOXeXOeOe", "XOXeOXOeXOOeeeXe", "XeOXOXeOeOeOeXee",
      "OOeOXXXeXeeeOeOX", "XOXeXeXeeeOOOOee", "XeeeeXXeeOOeXOeO", "OXeeeeeOOeeeeXOX", "OOeXeOOXeeXeXOOX",
      "OeeOeXeeeOOXXOXX", "XXOeeeeeeOXOOXeO", "eOeXeXOXOOeeXeXO", "eXeOeeOOOeXOXXOX", "eeOeXeOXXeeOeeOX",
      "OXeeOeeXXXOOOXXO", "OOOeXXeOeXeXOOXe", "eOeXOeeeOOeXeXXO", "eOOeXXOeOXXXeeeO", "XXXOeOOeeXXOeOOX",
      "OXOXXOeXXOOOOXeX", "OeXXOeeXeeOOOXOX", "eeXXOXOOeeXOeeeO", "XeXeOOOXXXeXOOOe", "eXOXOOOeXOXXOXeO",
      "XXeOeOXOOOeOXeXe", "XeOOXeXOeeeeOXXO", "OOXeeeOOeXeeOeXX", "eOeXXOeeeeXOXeOe", "XOOeOOXXXOeeeeXO",
      "OeeeXOXXOXXeeOeO", "OXOeOXXOXXOXXOeO", "OXeXOXeOeOeeXOee", "XeeeOXeOeOOeXeee", "XOeOeXOXOXOXeeOX",
      "eXeXeXeXeOXOeOOO", "XOeeeOeXeeOXeXOe", "OXeOOXXXeXOeeOOe", "OOXOOeXOXeOXXXeO", "OXOeXXXeeeOOXOXO",
      "eeeOOXeOOXOeXXXO", "eOeeOeOeeXXXOXOX", "OeeeXeOOXeXOXXOe", "eXXXeOOOeXXXOeOO", "OXXeXeeOOOXeOXee",
      "XXXeeeOOeOeeOeXO", "OOeXOXOXOXOeeXXO", "XeOXeeeeOeOOXeXO", "OOXXeXOeeXOXOeOe", "eOOeOeXXXOOXXOXO",
      "OXeeOeOXeeeeXOOX", "eXOOeeOeXXXOeOee", "OeXeXeXXeOeeOOXO", "XOXXeeeeOeOeeeOX", "OeXXOeOXXeOOXXOe",
      "OOOXXeXeeeXeeOOX", "XeeOeOOOOeXXeXee", "XeeXeeeeOeeXeeOO", "eOOOOXXeeOOXeXXX", "eeOeXeeOeeOeXeee",
      "OOXOeeOXeXOeXeeX", "OOXOeXXOeXeeeOOX", "eXOeeOXeeXeOOOXX", "OOeeXOeXOeeOXXXe", "eeXOOOeXeXOXXOOe",
      "OXXeXOOeOOeOXeXe", "eOXeOOXXOeXOeeee", "XeeXeeeeOOXeOXOO", "eOeXXXOeXeeeOOXO", "OOeeOXOXeOeeXXXe",
      "OXeXXXOOXOOeOOXe", "XXeOXOXOeeXOOeOe", "eeeOeXOXOeXeOOXe", "OOOXOXOOOXXeXeXe", "OXeOeXeOeeOXeeee",
      "XXeXOeOOeXXeeOOO", "XOOOeeXXeOeXXeeO", "XOXeeXOOeeOeeeXO", "XOeOeeeeXXXOOOeX", "eOeXOOOXOXeXeXOe",
      "XXOeeOXOeOXXOeee", "XeOXOOeOXeXXOeee", "OeXXeXOeeeeXOOOX", "OOeXXOeOOeOXXeXe", "OeOOOOXXXeXOXOXX",
      "XOXXXOXOeeeXOOOe", "eeXXeOOXeOeXXeOO", "XeXXOOXeXeeeeOOO", "OeXeOXeOeOeeOXeX", "eeXeXeeeeeXOOOeO",
      "eXeeeeOeeeOeXeOe", "eOXeXeOeeeOeeeOX", "XeOOOXXOOOXXXXeO", "XXOOeeXeeXOOeOXe", "OXXeeXOOOeXOXOee",
      "XOeeOeXeeOeXeeee", "XeOeOXXeXXOOOeee", "XeeOXOOXXeXOeeeO", "XOOXeeeOeOXOeXXe", "eeXOOeOXeeOeXXOe",
      "eeOOeeXXeXeOeOee", "OeXeeeOeeOeeXeXO", "eXeOXOXOOeeXOOXe", "eeOOeeeXXeXeOeOe", "eXeOeXXOeOOOXOXX",
      "XeeOeOeOeeeeXXOX", "eOXXOOeXeeXOOXeO", "eOXeOeOXeeXOOeXX", "OXOeOXeXXeXeOXOO", "OXOXXOeOXOXeeeeO",
      "OeeeXeXeeeOXXOeO", "eeeOOeeeXXXOXOee", "OXOOeeXOXOXXeOOX", "XeOeeXOOeeOXXOXO", "OOXOeXOOXXXOeeeX",
      "XeeXOOXeeeXOeXOO", "OeeeOXeOeOXXeeXO", "XOOOOOeOXeXXXXOe", "XeeXOOOXeeXeOOXe", "OXOeXXXOOeOXOeee",
      "OeXeOOOXXeeOeXOX", "XOeeXeXXXOOOeOXO", "OXOOXeXeXXOOXOXO", "OOOXeXeeeXeeOOXe", "XOOeeeXXOOOeXXOX",
      "OeXeOXOOeXXXXOOe", "eXeOOOXOeOXXeOeX", "eXeOOeeOXOOeXeeX", "XOOXOeeOeXeXOXOe", "XOXeeXXXOeeOOOeO",
      "XeeOOeeXOXOXXeOe", "OOXXeXOOeXeeOeXe", "OOXXeeeeOOOeXXee", "XXOeeXXOOOeeeOXO", "XeOXXOXOOeXeXOeO",
      "XeOOXOOeeeXXOOXe", "XXOOeeeeeeOOeXee", "eOeeeXOOeXXeeXOO", "XOeXeeOeOOOeeXXX", "eOXeeeeOXXOeOOeX",
      "OXeeOeXeeXOeOXXO", "XeXeXOeXOeOeOeeO", "OXeXeOeOXeOXOOXe", "XeOOeXOeeeXeXOee", "XXOOXOXeeXOeOOeX",
      "OXXeXeOeOOOXeOXX", "eOeOOeeXeeXXeeOX", "OOOXXeeOeXeOeXeX", "eeXXOXeXOOOeeOXO", "XeXeOeeOXOeXXOOO",
      "XOeXOOeXXXOOeOXO", "OXeOOOXOOXeXXeee", "OOXXXXOeXOOXOeXO", "XeeeXOOeeXeeOeee", "XOXOeXOeeeOXOOXX",
      "eeeOeOOXeXeOeXeX", "XeeOeeOXOOXOXXXO", "OOeXeOOXeOXeOXXe", "XeOXOeeOeXOXOeOX", "eeeXOeeeeOeeXXeO",
      "XXeOXeOXeeXOOXOO", "XOXOOeXeeXOeOeXe", "OeOOOeXOXOOXXXXe", "XeeeeXeeOOeXeOeO", "eOeeXXOXXOOXOOXO",
      "XeeOeeOXeXXeeOeO", "OOXOXOOOXXXeXOee", "eOOXXOeeeOXXeeeO", "OOeeXeeOXOeXeXOe", "eXOXXOXeOXeOOeXO",
      "OXeOeXOXeeOOOeXX", "eOXXOOOeeeOXXXOe", "XeOOeOeeeXXOeXOe", "XOeOOOOXOXeeXeXe", "eOOOOXeXeeXXOeXO",
      "OeOeXXeeeOXOXeOX", "OeOXXXeOOXOeeOXX", "eeOXOOeeeXXXeOOe", "OeOeeeXeXeeOOeeX", "eXOOeOeOXXXOOeXe",
      "eeeOeXXeeeeOeOXO", "OXeXOOXOOeeeXXOe", "XeOXeeOeeOeeXXeO", "XeOXeXeeOOeOeXeO", "XeOOXXeXOOeXOeXO",
      "XeOXeOXOOeXXXOeO", "OeeXeOXXXOOOOeXe", "OeeOeXOeeXXeOOXX", "OOXOOXeXXeOeXeee", "eOeOeXXXOOXeeeOe",
      "OeXOXXXOeOXXeOOe", "OeeOOeeXeXXeOeeX", "eOeeXeOXXXeeOOee", "OXeOXOeXeeeXXOOO", "XeeOeeeeOOeXXeee",
      "OXXeXOXXOeeXOOOe", "OeeOeeeXOeXOeeXe", "OXeOXOOXXeXOXOXO", "eeOOXXeXeOXXOeeO", "OeeeXXeeOeeeOeXe",
      "OeXXeeXOXOXeOXOO", "eeXXOOOXeOXOeeXe", "XOOeOXXOXXeeOOXe", "eXeXeXOXOeeOeXOO", "XeOOeXeeeeeOXeee",
      "OXeeeXOOOOXeXXXO", "eXeeOeeeOOeXXeOX", "eOXXeeOeOXXeeOXO", "OOeeeeeOXeXXXOOX", "XeOOOeXXOeXOOeeX",
      "eeeeeOeOXeXeXOXO", "eeeeXXOeeOeeeeeO", "XOeOeOOXeeeXXeXO", "eeOOXeOeOOeeXeXX", "OXeeOXeeOOXeXOXe",
      "XOeOXOXXOeeXOXOe", "OOOXXXeOeeOXOXOX", "XeXOXeOOXOXeeeOO", "eeeeeOOeeOXXOeXe", "OeeXeeeeeOXeXXOO",
      "OXXeeOXeeOeOXOXe", "eOXeXeeOOeeXXOOe", "OXeOOeeOXeXOXXee", "XeXOXeeeOeOOXeeO", "XXeOOeeeOXOOXeee",
      "OXXOOOOXeeXeXOee", "eXXXOeeOXOeOXeOe", "XeXeeeXOOeeOeOXO", "XeOeXeeeOXeOOXOX", "eXOOXOeXeeeeXeeO",
      "eeeOeeeXOXeeeOXO", "eXOeOOeXXXOeeXOO", "XOXeOeeXeOeOXOeX", "XXOeXOeeOeeOOXXe", "eXeeOeeXXOOOOXeX",
      "eXOXeeOeeOeeXeXO", "eeeXOeXeOeOeXOOX", "OXeeXXOeeOOXXOee", "XeeOXeXOXeOXOOee", "XeeOeeOeXOeOeXeX",
      "XOXOeXOeeXeOOXXO", "XXOeOOOeOXXXeOeX", "eeXXeOeOXOeeOXXO", "eeeOXXeOeXOeeOeX", "eOeeOeXeXXOeeXeO",
      "XOOXOOeOXeXXXOXO", "XeOXeOeeOeeXOeXe", "OXOXeeXXOeOeeeeO", "eXeXOOOeeXOOXeXO", "eeeeeeeXOXeeOOeX",
      "OOOXXOeeeOXeeXOX", "OOXeXOXeOeOXOeXX", "eeXOXeeXOOeOXeeO", "XeOeeXeeOXeXeeOO", "OOeOeeXOXXeeXOee",
      "eXOOXOeeeOXOeXOX", "OXOOeXeXXOeOOXee", "OXOOOeXeeeOXeXeX", "eeeeXOeOXOOeeXXe", "eeOOXeeOXeOeXXOX",
      "XXeOOeOOOeXOXXXe", "eeXeXOOOOXXXOXeO", "OOXOeOOeeXeeXOXX", "eXeOOOeXOXXeOXee", "eeeOXOOOOeeeeXXX",
      "OXeOXeOXXXOOOeee", "OXeOeeeXeeOXeOXe", "OXXXXeeeOeeOOeee", "OXOeOXXeOXOOeOXX", "OeXeXXeOeOOXeeXO",
      "XOOXeXeXOeXeXOOO", "eXOXeeXOOOXXeeOO", "eOOOOXeeeXXeeOeX", "eOeOeeXXeOeOXeOX", "eXXOeeOeXeXeeeOO",
      "eOeXOXeeeXXXOOeO", "OOXOXeXXOeeeOeee", "OXeOeXeXXOOeXeOe", "eeOOXXeOeOXXOeeX", "OeXXOeeeeXeeeOeO",
      "XOXeeOeXOXeXeOeO", "eeXOeOXXOXeOOOXe", "XOOeOXeeOeeXOeeX", "XeeXXOOOXeOeOXOX", "XXOOeXXOOOOXeXOX",
      "XeXeOeeXeOXOeeOe", "OeeeeOeXXeeOeeeX", "XXOOeOXOXeeXOOXO", "eeeXeXeOeeOOeeeX", "XeOeXXXeeeOXeOOO",
      "eOOeXeXXXeOeXOeO", "eeeeeOOXeXOeXXOO", "OOXOeXXOeXOXXOeO", "eeOOXOOXXXXOOeee", "eeeeOeOXXeOXeXOe",
      "OOOXXOeeXXOeeOeX", "eeeOXeeeOOeXeeee", "eXXeOOOeXXOOeeeX", "OXeXOOOeXOeeXOXX", "OOeOXeeXeOXeXeee",
      "eXeeeeOXXXeOeeOO", "OXeOeeOXeeOXXOXe", "XeOOXOXXOOXeXOee", "eXOOXXeOOOOeXXeX", "eOOeOXXeXeXOeXeO",
      "eeXXeeOOeOOXXeXO", "eXOOOXeXeOOeeXee", "OXeOXeOOOXeeXeXe", "eXeOeXeXeXeOXOOO", "eeXeeOeXXOOeOXOe",
      "XOXXOXOXOOeeOeee", "eeOeOXXeOOOXeeXe", "OXXOXeOOXOeeeeXO", "OXOOeOeeXXOeXeXe", "OOXXXOOeOeOXeXOX",
      "eOeOOeXeOXXeXOXe", "eeOeeOeeXOeOXXXO", "XOeOeOeXeeeOeeeX", "XeOOeeeXXOeeXeOe", "eOOOXOXOXOOXXeeX",
      "XOeeeeOXeeeOeeOX", "XOeOOeeXXOOXOeXe", "XXXeOOXXeOeOOeXO", "eOOXeXeXeOeeeXOO", "eOOXOeXOOXXOeOXX",
      "XeOXXOOOeeOXeXee", "eeeOeXOXOOXeeOXe", "OXOeeOeXeeOeXOeX", "eeeeXeOeOeXOeXee", "OXXeeeeOXOOeeeXe",
      "XOOOXeXOeXOeeeXe", "XXOOOOOXXXXeXeOO", "OXXeXeOOOeXXOOXe", "eOeXeeeOXOOXeeXe", "XeeOOXeeOeOeXeXe",
      "XXXeeOXXeeOeeOOO", "OXOeeXOOXOeeXOeX", "OeXXOXeXeOOOXOXO", "eOXeXXOOeeOXOXOe", "XXeeeOOOOXeeeeXO",
      "OXOeeeeXeeeOOXeX", "OOeeeXOXXOOeeeXe", "XeeOXOXeeXOeeeOe", "eXXeOXeXOOOXOeeO", "OeOOXOeXXOeXeeXO",
      "OeXXOXOXeXOOOXeO", "eeeeeeOeeeOXXOOX", "XOeOXXeXeeOOeOXe", "OOXOeeXeOXXXOeOe", "XeeXOeeOXOXXeOOO",
      "XOeOOOXeeeXeXXOe", "OXOeXOXXeOeOXXeO", "eXXOOOeXXOOOXOXX", "eeXeeOeeeOOXXeOX", "OOOeXeXOOXXeXOXe",
      "XOXeeOXOeXeOOeXO", "eeeOeeOXXeXeXOeO", "OXXOOeXOOeeXeeOX", "eOeeXeOXeeOXeeOe", "eOXXeOeeeeXXOeOe",
      "OOOXXXeeeXOXXOOe", "eeXeOXeeeXOOXOee", "OOXOXOeXXeXeOXOe", "XeOOOOXXXeOXeXOe", "OOeOOeXeXXOeeXeX",
      "XXXeOXOOOOeeOXXe", "XeXOeeOeeOXeXOeO", "XeXeeOOOOXOXXOOX", "XOXOeOeXXeOeOeOX", "eXOeXOXOeOeOeeeX",
      "OOXOeOXeOXXXXeOe", "XXeOeeOOOeXOXeee", "OeeOeOeeeeXOXOXX", "eeOOeOXeOeXeeXXO", "eOXXOeeOXXOeOOXX",
      "OeXeOXXOXeOXeOee", "OeXOeeeXeXXOOeOe", "eOXOOXOOXeOXeeeX", "eOeXeeeOeeeeXOXe", "eeOXeOeOeeXOXeOX",
      "OXXOeOOeeeeXXOeX", "XeOOXOXeOeOeOXXe", "XOeXOeOXOeeOXeXO", "eOOeXXXOeeOOXOXe", "XOeXXOOeeeOXXOOe",
      "eeOeOeeXOeOXXXOe", "OeXOOeOOeXXOeeXX", "OOeOeXeXXeeOXeXO", "eOOOeXeXOXeOeXeX", "XXXOOeXOOeOeOeXe",
      "eOOXXeXXXOeXOeOO", "eeOOOXeXeXXeOXOO", "eOeeeeeXeXOOOXee", "OeOXOOeOXeXXeeOX", "OXOOXeXXeeOXXOeO",
      "eOeeeXXOeeOOXXXO", "OeeeeXXeXOXOeeeO", "eXeXeOXeeXOeOOOX", "OOeXeXeOeeXOeeee", "XXOXXOOeOeOOeXXO",
      "OXeeeXXeOXeOXOeO", "OeOeOXeOXeXeXOOX", "XOOXeeOXOXeOOXeX", "XXeOeOOOeeOXXXee", "OOeeOXeeeeeXXXeO",
      "OeeOeeOXOOXeeeXX", "OOXOeeXeXXeeeXOO", "OXeeeeOXOOXeOeeX", "XXOeeOOeXeeXeOOe", "eeeXeOOOeeeXOXee",
      "eeeeOeOXeeeXOOeX", "eOXXXeeOO", "eOeOOXOXX", "eXOeeeeOX", "eXOXXOOOe", "OOXeeOXee", "XeXOeeOOX", "eXOOXOXOX",
      "eOOXeeXOe", "eOXeOeXeO", "XeeOeeeOX", "eOeOXeeee", "XeOOXXeOe", "eeeXXOOOe", "XOeOOXeXe", "eeOXOOeeX",
      "OeXeOeeee", "XeOXeeOXO", "OeXeeOOXe", "eOOOXeOXX", "eeXeeOeOe", "eXeeOeeee", "XeXeeOeOe", "OOXXeeOXO",
      "XOXOeOeXO", "XXeeOeOeO", "OeXXOeeee", "eOeeeXeOX", "XeOeOeXee", "OeeOOeeXX", "XeOOeXeOe", "XOXeOeeee",
      "eeXOeeeOX", "OeOeXXOXe", "eeeOXOXee", "OXXeXOOee", "eeOXeOOXe", "OeeOeOeXX", "XeOOeOXOX", "OXXeeeOXO",
      "OXeXeeeeO", "OXeeeeOeX", "OeeeeXeeO", "OXeeXeeOe", "OOeeXXOXO", "XeeXeOOOX", "OeeeeXOOX", "OeeXeOeXO",
      "eOXXeeOee", "OeeOeXeee", "eOXeeOeOX", "OXeeOeeeX", "eOOOeeeXX", "OXOOeeeXe", "XXeXOOeOe", "eeeeOeXXO",
      "XXOOOXeOX", "OeeeeeOeX", "eOOXXeXOe", "XeOOXOeXe", "eOXeeOeXO", "OeXeeeeOe", "eXXeOeOOe", "OOXeeOeeX",
      "eXOXeOXOe", "XOOeXeXOO", "eeOXXOOeX", "XeXXOOeeO", "eXOeeeXOO", "eOeeXOeXO", "OXOeeOeXe", "XXeeOXeOO",
      "eXeXOOeOX", "eOOOXeOXX", "XXeOeeOee", "XOeOOeXee", "eXOeOeeOX", "OOeeXeeXO", "OeOXXOeeX", "OeXeeeOeX",
      "eXeeeOeee", "eXeeOOXeO", "eeeOOXeee", "XOOOOXXXe", "OeOeOXeeX", "eeXOeXeeO", "eOOeXeeXO", "eeOeXOOXX",
      "eeeXeOOOX", "XeOOXOeXe", "XOOOXXXOe", "eeeXXOOee", "OeeeXXOee", "XXeOOeeOe", "XXeOOeOOX", "OOeeXXeee",
      "OOeOeeXeX", "eOXOeOeXe", "eXOeXeeOe", "eOeXOeXXO", "OXeeeOOeX", "eXOeOeeXe", "OXeOeXXOe", "eeeXeOeOX",
      "OXXeOeXOe", "OXXeeOXeO", "OeOOeXeeX", "eXOOeOeXe", "eXXOeOeXO", "OeeXeOOXe", "XeXeOOOee", "OOXeeeeeX",
      "XOeOXeXeO", "XeOeeOeee", "eOXOOXXXO", "XeeeXeOOe", "XOOeeXeee", "OeOXeeeXO", "eeeeeeeXO", "OeXeeXOXO",
      "eXXeOeeOO", "OXeeOXeOe", "OXeeOeeOX", "OeXXOOeee", "OeeXOXeOX", "eeeXeOeXO", "OXOeeOXeX", "eOOeeXOeX",
      "eOXeOeOXX", "eeXOeeeOX", "OXOXeXOXO", "OeOeXeeee", "eXOeXeeOO", "OOXXXeeOe", "eOXXOOeXe", "eeXeOOXOX",
      "OeXXOeOeX", "OOeeeXeXe", "eOXeOOeXX", "eXeXXOOeO", "XOOeeXXOe", "XOXXeeeOO", "eeXeXeeOO", "XeeOeeeOe",
      "eeOOeXXOX", "OeXeeeXOO", "XeXeeOXOO", "OeOOXXeXO", "OOXXXeOXO", "eeXOeXOee", "XOeeOeeeX", "eOOOXXXeO",
      "OXXOeeeOX", "XeeXXOOeO", "eOOXeeOXe", "eOeXeXeOe", "XOeOOXOXX", "eXeOXeXOO", "XeeXeOOOe", "OOeXeeXOX",
      "XOOeXeeeO", "XeeXOOOXO", "XOOOeXeXO", "eeeXOOeXe", "eeOOXXeXO", "eXOOeOXee", "eeXOeeOee", "eeeeeOOXX",
      "OeOeeXOeX", "eOeOXXeee", "OeOXeXOeX", "OOXeOXeXe", "XXOOOXeXO", "OeOeXXOOX", "XeeOXeeOe", "XeXOXOeeO",
      "XeeOeeeXO", "XOeOeeXeO", "OOeXOXXee", "eXeOeOeeX", "eXOOXeeee", "OXXeeeeOe", "OXeXOeXOe", "eOOXOeXee",
      "OeeOOXXeX", "OXOXeeeXO", "OOXXeeXOO", "eOOXeOXOX", "eOXOXeeee", "eXOXOOXOe", "eeXeXOeeO", "eXXXOeeOO",
      "XXOeOOXee", "XXeOOeXeO", "XOXeOeeXO", "OXOXeOXOX", "OOXeXXeOe", "OXXXOOOeX", "OeeOeOeXX", "eOeeeXOXe",
      "eeOOOeeXX", "eeOOXOXeX", "eOOOXOXeX", "XOXeOXeeO", "eOXXeOOee", "eeXXOXOeO", "OeOeXeOeX", "OXXOXOeeO",
      "OOeeeeXXe", "XOeeOOOXX", "eeOOOXeXe", "eXXOeeXOO", "OeeOXeeXe", "eOXOOeXXe", "OXOXXOOeX", "XeOOOXXOX",
      "XeeeeOOXO", "eOOOeeXeX", "XOeeOeeXe", "OeOOXeXee", "XOOeXXeeO", "OOeeXXXOO", "OeeXOOXeX", "eXXOeOOeX",
      "XeeOXeeeO", "XOXeOOXee", "eXOOOXeOX", "eOOXOOXXe", "XOeOeeOXX", "OXOeOXeee", "eXXOeOXeO", "eOXOOeeeX",
      "eOOeXeeXe", "OeeXXOXeO", "eXXOeeOee", "eeOeeXeOX", "OeOXOeeeX", "XeeOeeOOX", "eOeXXeOXO", "OeOeeXOXe",
      "eOeXOOOXX", "eOeeeOXXO", "XXOeOXXOO", "OeeeXOXeO", "XOeOXXOXO", "eeOOXeOXX", "OXOXeeeOe", "XOXXOOeXO",
      "XeXOeXOOe", "OOXOXeeeX", "eOXXXOeOe", "eOXXeOXOO", "eXXeOOXOe", "eeeeeXOOX", "XXOeeeeOe", "OXOOeXXee",
      "eeXOeOeXe", "eeeeXeOee", "XOeXeXOeO", "OeOeXXOee", "eXXOeeOXO", "eOeOXXOXe", "OXeXXOeeO", "eeOXXeeOO",
      "eOXOeeeee", "OOXeXOeee", "eXeeeXeOO", "OXOXXOOee", "eeXXOOOXe", "XeeXOOeee", "eeeOOXXee", "eXeOXeeOO",
      "OeOeeXXOX", "eeOOOXXXO", "eeeeeOeee", "eeXeXOOee", "XXOOXOeee", "OeOOXXXeO", "eOXeeOOeX", "XXeOeeOOe",
      "OOeXOeeXX", "OeXOeOXee", "OOeeXeXOX", "OeeXOOeeX", "OXeOXOXeO", "XOOeeeXXO", "eeXXOOeOX", "XOOeeXOXO",
      "eXeOeOeee", "OeeXeXOeO", "eeOXXeOeO", "eOeeXeeeO", "eXOeeXeeO", "eeeeOeeOX", "XXOOXOeee", "eOeXXOOXO",
      "eOXOeOeXX", "eeeeXOOeX", "eeeOeXXOe", "OeOXeeXOe", "XOXOeeXOO", "OXXeeOOXe", "eOOOXXXeO", "OOeOOXXeX",
      "XeOeOeXOe", "OXeOOeXeX", "eOXXeOOXO", "eOeeXeOeX", "OeeeXOXXO", "XOOXeXOOe", "XOOeXXeOe", "eXeeeeeOe",
      "eeOXOXeeO", "OeOOeXXXe", "OeXXOOOXe", "eXXeOOOXe", "XXOOeeeee", "eOXeXOeXO", "eXXOOeOOX", "OeeXeXeOe",
      "XOOXXeeOe", "XOOXXOOee", "OOXXXeeeO", "eXeOOXXOO", "XOOeeOXeX", "OeXXeOXOe", "XOeXOOeXO", "eeXOeOOXe",
      "OeXOeXXOO", "XeOeeXOeO", "XeXXOOOOX", "XXeOOXeeO", "OeeeeXOOX", "eeXeeeeOO", "OXXeOOOXe", "XOOeXXeOO",
      "eXXOeOOXO", "eOeXOeeXO", "XeeOOeOeX", "OeeOeeeeX", "eeXeOXOXO", "eeeeOXeee", "eeeOXXeeO", "eeeOeOeeX",
      "OXeXOeXOe", "OeOeXOeXX", "OXeeeOOXX", "OeOXeXOXO", "eXOOeeeOX", "OeXeXeeOO", "eeeOeeeXe", "XXOeXeOOe",
      "eXXOeXOOe", "eOXeeOeXO", "OOeOXeXXe", "OeeXOXOeX", "XOOOeXeXO", "XOXOXOeXO", "XeOeXOOXe", "OOeeOXeXe",
      "OeOXeeeXe", "OXXOeeeXO", "eeOXOXeOe", "eeOeeXeOe", "XXeOeOXOO", "XeOXeeOeO", "eXOXeeXOO", "OeXeeOXOX",
      "OOeXXOXOe", "eeOeeXeOX", "eOXOeOeeX", "XXOOXeOeO", "OeeeeeOXX", "OXOOeeXeX", "XOeeOXOXe", "eOeeOXXXO",
      "OeXeeeXOe", "OeXeeeXeO", "OOXeXOOeX", "OOXXeOOeX", "eXeeOXXOO", "eOeXOOeeX", "eOeOXeeeX", "XOeOeeeee",
      "eOXeeOXOe", "OeXXeOeee", "XOXeXeOeO", "eeXOeXeOO", "XOOeeXeXO", "OOeXXeOOX", "eOeOXOeXe", "XeOOXeXOe",
      "OeeOeeXOX", "eXXeOOOeX", "OeeXeOeee", "OeeeOOXXe", "eXXOeeXOO", "OeeXXOOeX", "OeXXeOOee", "eeXXOOXOe",
      "XOOXOXeeO", "OOXXeeOXe", "eeXXOeOXO", "eOXeeOXeO", "eXOXeXOeO", "OeOeXeeXe", "eXOeeeXeO", "OeOeOXXXe",
      "OeeXeXOOe", "XeOOOeXee", "OXeeOOeeX", "XeOeOeeXe", "OeOeXXeOe", "OeOeeXOXe", "OeOXeXXeO", "eXXeOeOOe",
      "eXOOOXeeX", "XeXeOeeeO", "OXXOOXXOe", "OeXXeOOOX", "OOeeXeOXe", "OOeXXOXOX", "eOeeeXOee", "eOOeXXeee",
      "eOOeeXeXe", "eOeOeOXeX", "OeeeXOOeX", "XeXeeeOOe", "XeOeOeeOX", "eXOeeeeOe", "eeXXeOOXO", "XeOeOeXOe",
      "eeXeOOOXX", "eXXOOeeXO", "XXOeOOeee", "eXOOXOOeX", "eOeXeeeXO", "eOOXeeXOe", "eeOOXeXOX", "eeXOeXOeO",
      "OeeeOXXee", "OeOOXXXOe", "XXeOXOeOO", "OXeeOXOOX", "eXeeOXeeO", "eOeeXeeOe", "OeOXOeXeX", "eOXOeeOXX",
      "OeeeXeeOe", "eXOOeOOXX", "eXOeOXeOe", "eOOXXOOeX", "XOOeOXXeO", "eXXOOXeOO", "OXeOOXXOe", "eOOXeOeeX",
      "eOOOeeeXX", "OXeXOOeee", "OXeeOOXOX", "XOeOXXeOO", "eeeeeeeXO" })
  public void testGraphContains(String str) {

    if (str.length() == 9) {
      try {
        assertTrue(str, r3x3.contains(new TicTacToeNxN(str)));
      } catch (InvalidBoardString e) {
        e.printStackTrace();
      }
    }
  }

}
